[project]
name = "dashboard-school"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.3.0",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.2.250926",
    "plotly>=6.5.0",
    "scikit-learn>=1.7.2",
    "sqlalchemy>=2.0.44"
]